### ISSUE TITLE
Alex token metadata link returns error

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/token-metadata-api#128]

**Comment by rafaelcr** [comment]
Another example: https://api.hiro.so/metadata/v1/nft/SP1CSHTKVHMMQJ7PRQRFYW6SB4QAW6SR3XY2F81PA.crash-punks-vip-pass/263

**Comment by rafaelcr** [comment]
Another: https://api.mainnet.hiro.so/metadata/ft/SP125J1ADVYWGWB9NQRCVGKYAG73R17ZNMV17XEJ7.slime-token

This looks like it happens when JSON5 can't parse the metadata URI response: https://bitcoinmonkeys.io/
```
SyntaxError: JSON5: invalid character '<' at 1:1
    at syntaxError (/app/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/app/node_modules/json5/lib/parse.js:1055:12)
    at Object.value (/app/node_modules/json5/lib/parse.js:309:15)
    at lex (/app/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/app/node_modules/json5/lib/parse.js:25:17)
    at getMetadataFromUri (/app/dist/src/token-processor/util/metadata-helpers.js:235:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAllMetadataLocalesFromBaseUri (/app/dist/src/token-processor/util/metadata-helpers.js:32:29)
    at async ProcessTokenJob.handleFt (/app/dist/src/token-processor/queue/job/process-token-job.js:96:31)
    at async ProcessTokenJob.handler (/app/dist/src/token-processor/queue/job/process-token-job.js:48:21)
```
